# Generated by Django 3.2.6 on 2021-08-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('picture', models.FileField(upload_to='')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Middle', 'Middle'), ('High', 'High')], max_length=10)),
            ],
        ),
    ]
