# Generated by Django 3.2.6 on 2021-08-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
