# Generated by Django 3.2.6 on 2021-09-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todomodel_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('Low', 'yabiku01'), ('Middle', 'yabiku02'), ('High', 'yabiku03')], max_length=10),
        ),
    ]
