# Generated by Django 3.2.6 on 2021-09-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todomodel_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('A', 'Low'), ('B', 'Middle'), ('C', 'High')], max_length=10),
        ),
    ]
